variables:
  - :"Numéro de licence"
  - :"Statut (finisher, DNP…)"
  - :"Téléphone"
  - :"Email"
  - :"Nom"
  - :"Prénom"
  - :"Sexe"
  - :"Date de naissance"
  - :"Club"
  - :"Rang final"
  - :"Temps final"
  - :"Sexe"
  - :"Rang par sexe"
  - :"Rang par catégorie"
  - :"Catégorie"
  - :"Distance de l’épreuve"
  - :"Type de discipline 1"
  - :"Type de temps 1"
  - :"Temps 1"
  - :"Rang 1"
  - :"Type de discipline 2"
  - :"Type de temps 2"
  - :"Temps 2"
  - :"Rang 2"
  - :"Type de discipline 3"
  - :"Type de temps 3"
  - :"Temps 3"
  - :"Rang 3"
  - :"Type de discipline 4"
  - :"Type de temps 4"
  - :"Temps 4"
  - :"Rang 4"
  - :"Type de discipline 5"
  - :"Type de temps 5"
  - :"Temps 5"
  - :"Rang 5"
  - :"Type de discipline 6"
  - :"Type de temps 6"
  - :"Temps 6"
  - :"Rang 6"
  - :"Type de discipline 7"
  - :"Type de temps 7"
  - :"Temps 7"
  - :"Rang 7"
  - :"Type de discipline 8"
  - :"Type de temps 8"
  - :"Temps 8"
  - :"Rang 8"
  - :"Type de discipline 9"
  - :"Type de temps 9"
  - :"Temps 9"
  - :"Rang 9"
  - :"Type de discipline 10"
  - :"Type de temps 10"
  - :"Temps 10"
  - :"Rang 10"
